services:
  react-native:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    build: ./react-native/.devcontainer
    container_name: react-native
    ports:
      - "8081:8081"
    volumes:
      - .:/morphtic
    working_dir: /morphtic/react-native
    # command: >
    #   sh -c "yarn install && yarn start"
    command: sleep infinity
    env_file:
      - ./react-native/.devcontainer/.env
