services:
  react-native:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    build: ./react-native/.devcontainer
    container_name: react-native
    ports:
      - "8081:8081"
    volumes:
      - .:/morphtic
    working_dir: /morphtic/react-native
    # command: >
    #   sh -c "yarn install && yarn start"
    command: sleep infinity
    env_file:
      - ./react-native/.devcontainer/.env
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./dynamodb-local:/home/dynamodb-local/data"
    working_dir: /home/dynamodb-local
  magnito:
    image: frourio/magnito:latest
    ports:
      - 5050:5050 # Cognito API
      - 5051:5051 # web interface
      - 5052:5052 # OAuth2 SSL endpoint
    environment:
      COGNITO_USER_POOL_ID: ap-northeast-1_morphtic
      COGNITO_USER_POOL_CLIENT_ID: reactnative
      COGNITO_ACCESS_KEY: magnito-access-key
      COGNITO_SECRET_KEY: magnito-secret-key
      COGNITO_REGION: ap-northeast-1
      SMTP_HOST: inbucket
      SMTP_PORT: 2500
      SMTP_USER: fake_mail_user
      SMTP_PASS: fake_mail_password
    volumes:
      - magnito:/usr/src/app/data
  inbucket:
    image: inbucket/inbucket:3.0.3
    ports:
      - 2500:2500 # SMTP
      - 9000:9000 # web interface
    volumes:
      - inbucket:/storage
volumes:
  dynamodb-local:
    driver: local
  magnito:
    driver: local
  inbucket:
    driver: local
